# Generated by Django 6.0 on 2025-12-26 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0002_remove_offer_price_offer_image_offer_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offer',
        ),
        migrations.AddField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='marketplace_app.offerdetail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='in_progress', max_length=30),
        ),
    ]
